# Generated by Django 3.0 on 2022-06-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20220614_2031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
